######################################################################
# Automatically generated by qmake (1.07a) Mon Jul 3 23:45:09 2006
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += vu_meter.h
SOURCES += vu_meter.cpp
